[package]
name = "terminal_termion"
version = "0.1.0"
authors = ["Rudi Benkovic <rudi.benkovic@gmail.com>"]

[dependencies]
terminal_cli = { path = "../cli_core/" }
termion = { git = "https://gitlab.redox-os.org/Jezza/termion", rev = "9e35f915" }

[target.'cfg(unix)'.dependencies]
libc = "0.2.8"