[package]
name = "terminal_crossterm"
version = "0.1.0"
authors = ["Rudi Benkovic <rudi.benkovic@gmail.com>"]
edition = "2018"

[dependencies]
terminal_cli = { path = "../cli_core/" }
crossterm = "0.18"